// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUIRecordPlayback
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinTreeItem uIDesktopTreeItem = this.UIFileExplorerWindow.UITreeViewWindow.UIDesktopTreeItem.UIThisPCTreeItem.UIDesktopTreeItem;
            WinTreeItem uIDocumentsTreeItem = this.UIFileExplorerWindow.UITreeViewWindow.UIDesktopTreeItem.UIThisPCTreeItem.UIDocumentsTreeItem;
            WinTreeItem uIDownloadsTreeItem = this.UIFileExplorerWindow.UITreeViewWindow.UIDesktopTreeItem.UIThisPCTreeItem.UIDownloadsTreeItem;
            #endregion

            // Last mouse action was not recorded.

            // Click 'Desktop' -> 'This PC' -> 'Desktop' tree item
            Mouse.Click(uIDesktopTreeItem, new Point(45, 10));

            // Click 'Desktop' -> 'This PC' -> 'Documents' tree item
            Mouse.Click(uIDocumentsTreeItem, new Point(34, 12));

            // Click 'Desktop' -> 'This PC' -> 'Downloads' tree item
            Mouse.Click(uIDownloadsTreeItem, new Point(31, 12));
        }
        
        #region Properties
        public UIFileExplorerWindow UIFileExplorerWindow
        {
            get
            {
                if ((this.mUIFileExplorerWindow == null))
                {
                    this.mUIFileExplorerWindow = new UIFileExplorerWindow();
                }
                return this.mUIFileExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFileExplorerWindow mUIFileExplorerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIFileExplorerWindow : WinWindow
    {
        
        public UIFileExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "File Explorer";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("File Explorer");
            this.WindowTitles.Add("Desktop");
            this.WindowTitles.Add("Documents");
            #endregion
        }
        
        #region Properties
        public UITreeViewWindow UITreeViewWindow
        {
            get
            {
                if ((this.mUITreeViewWindow == null))
                {
                    this.mUITreeViewWindow = new UITreeViewWindow(this);
                }
                return this.mUITreeViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITreeViewWindow mUITreeViewWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITreeViewWindow : WinWindow
    {
        
        public UITreeViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "100";
            this.WindowTitles.Add("File Explorer");
            this.WindowTitles.Add("Desktop");
            this.WindowTitles.Add("Documents");
            #endregion
        }
        
        #region Properties
        public UIDesktopTreeItem UIDesktopTreeItem
        {
            get
            {
                if ((this.mUIDesktopTreeItem == null))
                {
                    this.mUIDesktopTreeItem = new UIDesktopTreeItem(this);
                }
                return this.mUIDesktopTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIDesktopTreeItem mUIDesktopTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDesktopTreeItem : WinTreeItem
    {
        
        public UIDesktopTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Desktop";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("File Explorer");
            this.WindowTitles.Add("Desktop");
            this.WindowTitles.Add("Documents");
            #endregion
        }
        
        #region Properties
        public UIThisPCTreeItem UIThisPCTreeItem
        {
            get
            {
                if ((this.mUIThisPCTreeItem == null))
                {
                    this.mUIThisPCTreeItem = new UIThisPCTreeItem(this);
                }
                return this.mUIThisPCTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIThisPCTreeItem mUIThisPCTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIThisPCTreeItem : WinTreeItem
    {
        
        public UIThisPCTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "This PC";
            this.SearchProperties["Value"] = "1";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.SearchConfigurations.Add(SearchConfiguration.NextSibling);
            this.WindowTitles.Add("File Explorer");
            this.WindowTitles.Add("Desktop");
            this.WindowTitles.Add("Documents");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIDesktopTreeItem
        {
            get
            {
                if ((this.mUIDesktopTreeItem == null))
                {
                    this.mUIDesktopTreeItem = new WinTreeItem(this);
                    #region Search Criteria
                    this.mUIDesktopTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Desktop";
                    this.mUIDesktopTreeItem.SearchProperties["Value"] = "2";
                    this.mUIDesktopTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIDesktopTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIDesktopTreeItem.WindowTitles.Add("File Explorer");
                    #endregion
                }
                return this.mUIDesktopTreeItem;
            }
        }
        
        public WinTreeItem UIDocumentsTreeItem
        {
            get
            {
                if ((this.mUIDocumentsTreeItem == null))
                {
                    this.mUIDocumentsTreeItem = new WinTreeItem(this);
                    #region Search Criteria
                    this.mUIDocumentsTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Documents";
                    this.mUIDocumentsTreeItem.SearchProperties["Value"] = "2";
                    this.mUIDocumentsTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIDocumentsTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIDocumentsTreeItem.WindowTitles.Add("Desktop");
                    #endregion
                }
                return this.mUIDocumentsTreeItem;
            }
        }
        
        public WinTreeItem UIDownloadsTreeItem
        {
            get
            {
                if ((this.mUIDownloadsTreeItem == null))
                {
                    this.mUIDownloadsTreeItem = new WinTreeItem(this);
                    #region Search Criteria
                    this.mUIDownloadsTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Downloads";
                    this.mUIDownloadsTreeItem.SearchProperties["Value"] = "2";
                    this.mUIDownloadsTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIDownloadsTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIDownloadsTreeItem.WindowTitles.Add("Documents");
                    #endregion
                }
                return this.mUIDownloadsTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIDesktopTreeItem;
        
        private WinTreeItem mUIDocumentsTreeItem;
        
        private WinTreeItem mUIDownloadsTreeItem;
        #endregion
    }
}
